### ISSUE TITLE
Help with menu

### ISSUE THREAD

**Issue by vshanecurtis** [PhoenixPE/PhoenixPE#118]
﻿Could you please provide some guidance as to which menu tool and the options that would produce a menu that most closely resembles a Win 11 single column menu.  I am going crazy testing all the various tools and options.  Also, is it possible to forgo having a menu altogether, like Win 8 (threw up in my mouth just typing it.) My PE will not have many apps to start and I'm considering just using desktop shortcuts and using task bar shortcuts for my most used  apps.

**Comment by homes32** [comment]
Modify the `Start Menu Folder` box to contain a period `.`

This will place all shortcuts on the root level of the `All Programs` folder similar to the Win10/Win11 start menu. (no sub-folders)

![image](https://github.com/user-attachments/assets/4c640584-5221-46a5-82ac-a3754abcf942)

If you just have a handful of apps, you can also use the checkbox to Pin to Start Menu, and they will all be on the main start menu screen.

**Comment by vshanecurtis** [comment]
Mr. Holmgren,

Thank you for your assistance in solving these issues.  It is much appreciated.

Yes, initially my PE will have just a few apps.  The ones I use most often when I'm in Tech mode, Partition Assistant and Macrium Reflect.  I'm also going to include NTSetup because I want to be able install Windows without having to use multiple USBs or CDs.  Once I get the PE where I want it, I'm going to partition my USB and copy one of my multi-version Windows ISOs to the second partition.  I'll still have more than enough room on my USB to add things to my PE as I need to.

I think you misunderstood what I was saying about the menu.  If I decide to have a menu on my PE, I want it to look like a blank one column Win 11 menu.  I have tried to get what I want using the menu tools available in Pheonix and I can't seem to get it.  I end up with everything but what I want.  Which menu tool and what combination of its options will get me what I want or something close.  I've tried until I'm blue in the face and I can't get it.

I found a collection of scripts that worked with Winbuilder.  They are referred to as MoPlugins.  Would you like me to send them to you.  Might be some good stuff in there that you can modify and incorporate into your project.

What programming language are you using for development.  I'm guessing C.  I have not looked at the source code.  I don't like C.  I think it is overused.  It is treated like a general-purpose language and it most certainly is not.  It was meant as a high-level language alternative to using assembler.  It was never intended to be used as a development language.  Now every programmer in creation uses it for everything under the sun.

I assume that you'll be adding the folder and document icons to the treeview at some point.  It's easy enough.  I like using treeviews.  They are actually fun to mess with.  If you need assistance with anything other than coding in C, let me know.  If I can help, I would be happy to.  I can send you a copy of my resume if you would like.  I have two BS degrees from DeVry University, Computer Information Systems and Information Technology.

Thanks Again,
Shane Curtis

________________________________

**Comment by homes32** [comment]
Unfortunately, the Win11 start menu is non-function in WinPE, so we are stuck with what the 3rd party alternatives provide for styles & themes. If you can't find something you like you may have better luck submitting a request to the developers of that software.

PhoenixPE & PEBakery use a wide variety of programming languages, each with their own advantages.

The PEBakery script engine is built with C# using .Net Core 6 and WPF, with some low level stuff written in C for performance (Wim handling, archiving, etc.)
The GUI launcher uses C++ in order to provide an error message to the user and download options if the user does not have the .Net Core runtime installed.
The build scripts themselves are written in a custom script format.
Utility programs used inside PhoenixPE are written C, AutoIT, and Purebasic depending on their function and these languages are chosen for their small executable size and no external runtime dependencies.
Utility programs used during the build process use C/C++, AutoIT, Purebasic, .NET, batch, and powershell depending on their function.

each language has its purpose. use what makes the best sense for the job you need to do! :)

**Comment by vshanecurtis** [comment]
Mr. Holmgren,

Thank you for your reply.

Yes, I agree with you.  Pick the tool best suited for the job.   Too many programmers want to use C as the end all be all solution for everything.  I have experience with a number of languages, including numerous forms of BASIC, old school original basic and different forms of Business BASIC.  If you need some help in that area, or any other, let me know.

The install scripts look like old school install scripts from the days when software was distributed on disks and CD's.

Also, I was able to resolve the issue with Virtualbox.  I required a BIOS update.

Shane Curtis
________________________________
