### ISSUE TITLE
MiscShortcuts.script: Regedit is in %Windir%, not in %Windir%\System32

### ISSUE THREAD

**Issue by Rolf185** [PhoenixPE/PhoenixPE#33]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿Please update:

If,%cb_regedit_DesktopShc%,Equal,True,AddShortcut,Desktop,"",%txt_regedit_ShortcutName%,"**#$pWinDir#$p\regedit.exe**"
If,%cb_regedit_StartMenuShc%,Equal,True,AddShortcut,StartMenu,%txt_regedit_StartMenuFolder%,%txt_regedit_ShortcutName%,"**#$pWinDir#$p\regedit.exe**"
If,%cb_regedit_PinToTaskbar%,Equal,True,PinShortcut,Taskbar,Auto,"**#$pWinDir#$p\regedit.exe**"
If,%cb_regedit_PinToStartMenu%,Equal,True,PinShortcut,StartMenu,Auto,"**#$pWinDir#$p\regedit.exe**"

**Comment by homes32** [comment]
This was actually fixed in commit cbcc441420f8e5e9331a0abf9de7b68e6dfb1280 and is included in the [latest release](https://github.com/PhoenixPE/PhoenixPE/releases/tag/2023.01.30) on 2023-01-30. you will want to download the latest release package or grab the [updated script](https://github.com/PhoenixPE/PhoenixPE/blob/master/Projects/PhoenixPE/Tweaks/MiscShortcuts.script) form the master branch.
