### ISSUE TITLE
Localization script always throws error.

### ISSUE THREAD

**Issue by ElektroStudios** [PhoenixPE/PhoenixPE#38]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
These are my 'Localization' script settings:

![](https://i.imgur.com/TWtlwe0.png)

The issue is that when I check the 'Localization' script checkbox and start a build, it always throws the next error:

![](https://i.imgur.com/pRAWcob.png)

```
- [3] Warnings in script [Localization] (PhoenixPE\Tweaks\Localization.script)
[Warning] Halt - Error: Dism.exe terminated with error code: [87]. Check the log for details. (If,Not,#r,Equal,0,Halt,"Error: Dism.exe terminated with error code: [#r]. Check the log for details.") (Line 199)
[Warning] Echo - An error occurred building PhoenixPE. Please check the build log for details.
```

![](https://i.imgur.com/ModtOGi.png)

---------------------------------

### NOTE that I'm using the recommended 'Win10_2004_English_x64.iso'. I also tested with 'Win10_2004_Spanish_x64.iso', both were downloaded with [FIDO](https://github.com/pbatard/Fido).

![](https://i.imgur.com/ou5ZIzs.png)

I also tried doing the most minimal possible changes from my side, which are: 1. download PhoenixPE and run it, 2. set the source image, 3. enable and set the Localization settings, and finally start the build. It always throws this damn error.

-------------------------------------------

Full DIsm log: [dism.log](https://github.com/PhoenixPE/PhoenixPE/files/11346722/dism.log)

Partial Dism log lines:

```
2023-04-27 20:07:18, Info                  CBS    Failed to find a matching version for servicing stack: C:\PhoenixPE\Workbench\PhoenixPE\Target\Windows\WinSxS\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.19041.262_none_e73f0197262d9fec\ [HRESULT = 0x80070490 - ERROR_NOT_FOUND]
2023-04-27 20:07:18, Info                  CBS    Failed to find servicing stack directory in online store. [HRESULT = 0x80070490 - ERROR_NOT_FOUND]
2023-04-27 20:07:18, Info                  CBS    Offline servicing, using stack version from: C:\PhoenixPE\Workbench\PhoenixPE\Target\Windows\WinSxS\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.19041.262_none_e73f0197262d9fec\cbscore.dll
2023-04-27 20:07:18, Info                  CBS    Loaded Servicing Stack v10.0.19041.262 with Core: C:\PhoenixPE\Workbench\PhoenixPE\Target\Windows\WinSxS\amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.19041.262_none_e73f0197262d9fec\cbscore.dll
```

Full build log: [BuildLog_2023_04_27_200348_Project_PhoenixPE.txt](https://github.com/PhoenixPE/PhoenixPE/files/11346747/BuildLog_2023_04_27_200348_Project_PhoenixPE.txt)

Full compressed support log: https://www.mediafire.com/file/vnpgkybplkfykhz/2023-04-27-2008-PhoenixPE-Logs.7z/file

---------------------------------

Not sure if relevant, but these two manifest files are inside the directory ..\Workbench\PhoenixPE\Target\Windows\WinSxS\Manifests:

 - amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.19041.1_none_bf506ecc66a800df
 - amd64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.19041.262_none_e73f0197262d9fec
 
-----------------------------

final note: 
My host OS (from where I'm running PhoenixPE / PEBakery) it is Windows 10 2004 x64 v10.0.19041.450
The Dism.exe version in my host OS it is v10.0.19041.329

Not sure if and how can I update it.

------------------------------------------------------

EDIT:

I ended looking [here](https://learn.microsoft.com/en-us/windows/deployment/update/servicing-stack-updates#why-should-servicing-stack-updates-be-installed-and-kept-up-to-date) and then here: https://www.catalog.update.microsoft.com/Search.aspx?q=KB5005260 - but I don't know if this is what I need in order to update to the required DISM version that I think PhoenixPE is trying to request, and anyways I have Windows Update removed through NTLite in my host OS...   so...?...

What a headache all this.

------------------------------------------------------

I've followed [these](https://stackoverflow.com/a/55180034/1248295) instructions to install the MSU package of the Servicing Stack update for my Win10 2004 (without Windows Update), but the problem persists.

I also tried to just copy all the related DISM files and folders from the source ISO (the servicing packages and catalogs and manifests from WinSXS directory, and from .\Windows\Servicing\Stack dir) to my host OS, but the problem persists.

And I'm doing all this without really having clear whether this error it is a PhoenixPE bug or maybe it is because I'm missing something in my host OS related to DISM / Servicing stack.

I only can say that I didn't had any problem to personalize the keyboard layout and regional settings with WinBuilder.

**Comment by homes32** [comment]
first of all, thank you for the detailed report and for actually supplying the compressed support log!!!!

The servicing stack messages are red herrings and are really just informational. The actual bug is surprisingly simple and due to an incorrect variable reference.

change line 70 from
```
StrFormat,POS,%UserLocale%,),%Pos%
```
to
```
StrFormat,POS,%cmb_UserLocale%,),%Pos%
```

I'll get this patched shortly. Thank you for the report!

**Comment by ElektroStudios** [comment]
Thanks again. :)

**Comment by ElektroStudios** [comment]
> first of all, thank you for the detailed report and for actually supplying the compressed support log!!!!
> 
> The servicing stack messages are red herrings and are really just informational. The actual bug is surprisingly simple and due to an incorrect variable reference.
> 
> change line 70 from
> 
> ```
> StrFormat,POS,%UserLocale%,),%Pos%
> ```
> 
> to
> 
> ```
> StrFormat,POS,%cmb_UserLocale%,),%Pos%
> ```
> 
> I'll get this patched shortly. Thank you for the report!

That single change itself does not fix the issue for me (I applied the change by pressing "Edit script source" button), but I suppose you will get this fixed when you can.

**Comment by ElektroStudios** [comment]
While the bug gets fixed I  researched and wrote this simple batch-script to change the keyboard layout on the boot.wim file:

```
@ECHO OFF

SET "bootwimFilePath=C:\PhoenixPE\Output\PhoenixPE_en-US_x64\sources\Boot.wim"
SET "bootwimImageIndex=1"
SET "mountDirPath=%homedrive%\mount_BootWinPE"

:: https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-packs
SET "layoutCode=0C0A:0000040A" & REM Spanish [Spain] [es-ES]

COLOR 07
ECHO:This script will change the keyboard layout
ECHO:for the specified boot.wim image from a WinPE ISO. 
ECHO+
ECHO:CURRENT SCRIPT CONFIG:
ECHO:----------------------
ECHO:Boot.wim File Path..: "%bootwimFilePath%"
ECHO:Boot.wim Image Index: "%bootwimImageIndex%"
ECHO:Mount Directory Path: "%mountDirPath%"
ECHO:Keyboard Layout Code: "%layoutCode%"
ECHO+
CHOICE /C "YN" /M "Continue"
IF "%ERRORLEVEL%" EQU "2" (EXIT /B 0)
CLS

MKDIR "%mountDirPath%" 2>NUL

DISM.exe /mount-image /imagefile:"%bootwimFilePath%" /index:%bootwimImageIndex% /mountdir:"%mountDirPath%"
IF %ERRORLEVEL% NEQ 0 (GOTO:SHOW_ERROR_SCREEN)
CLS

DISM.exe /image:"%mountDirPath%" /Set-InputLocale:"%layoutCode%" 
IF %ERRORLEVEL% NEQ 0 (GOTO:SHOW_ERROR_SCREEN)
CLS

DISM.exe /image:"%mountDirPath%" /get-intl
IF %ERRORLEVEL% NEQ 0 (GOTO:SHOW_ERROR_SCREEN)

DISM.exe /unmount-image /mountdir:"%mountDirPath%" /commit
IF %ERRORLEVEL% NEQ 0 (GOTO:SHOW_ERROR_SCREEN)

:SHOW_GOODBYE_SCREEN
COLOR 0A
ECHO+ 
ECHO:Finished.
ECHO+
PAUSE
EXIT /B 0

:SHOW_ERROR_SCREEN
COLOR 0C
ECHO+
ECHO:ERROR FOUND. THE PROGRAM WILL TERMINATE NOW.
ECHO+
PAUSE
EXIT /B 1
```

Before using it, set the correct values for the **bootwimFilePath**, **bootwimImageIndex**, **mountDirPath** and **layoutCode** variables.

**Comment by Fred-Vatin** [comment]
Hi,

I think this issue can be reopened because I have the same error on last build.

```
1 warning in script [Localization] (PhoenixPE\Tweaks\410-Localization.script)
Halt - Error: Dism.exe terminated with error code: [87]. Check the log for details. (If,Not,#r,Equal,0,Halt,"Error: Dism.exe terminated with error code: [#r]. Check the log for details.") (Line 209)
```

In the localization script, here is the part causing the error.

```ini
// Set Keyboard, Format and Timezone with DISM
If,Not,%DismArg%,Equal,"",Begin
  Echo,"Configuring International Settings..."
  DISM,"/image:#$q%TargetDir%#$q %DismArg% /LogPath:#$q%DismLog%#$q"
  If,Not,#r,Equal,0,Halt,"Error: Dism.exe terminated with error code: [#r]. Check the log for details."
End
```

Here is my setup:

<img width="849" height="351" alt="Image" src="https://github.com/user-attachments/assets/28454d4a-5f1c-4687-b888-6d72cb38b41a" />


Here is the full log: https://www.mediafire.com/file/gwj40c55rxbr80p/2025-08-03-2043-PhoenixPE-SupportBundle.zip/file

I will test any fix you would want me to try and report.

---



<details>
  <summary>Beginning of BuildLog</summary>

<pre><code>
- PEBakery Build <Project PhoenixPE> -
Built    by PEBakery 1.2.0-develop
Exported by PEBakery 1.2.0-develop

Started  | 2025-08-03 08:33:10 PM +02:00


<Host Environment>
Windows      | 10.0.19045.0 (x64)
.NET Runtime | 8.0.17 (x64)


<Log Statistics>
Success      : 48429
Warning      : 1
Overwrite    : 92
Error        : 0
Info         : 22295
Ignore       : 17265
Muted        : 1


<Warnings>
- [1] Warning in script [Localization] (PhoenixPE\Tweaks\410-Localization.script)
[Warning] Halt - Error: Dism.exe terminated with error code: [87]. Check the log for details. (If,Not,#r,Equal,0,Halt,"Error: Dism.exe terminated with error code: [#r]. Check the log for details.") (Line 209)


<Scripts>
[  1/ 21] PhoenixPE v1.0.9.0              |   0.1s | PhoenixPE\script.project
[  2/ 21] Source Config v1.1.4.0          |   0.9s | PhoenixPE\100-ConfigSource.script
[  3/ 21] Pre-Flight Check v1.2.1.0       |   1.2s | PhoenixPE\Core\200-PreFlight.script
[  4/ 21] Core Files v1.3.1.0             |  74.3s | PhoenixPE\Core\210-Core.script
[  5/ 21] Core Registry v1.1.1.0          | 299.5s | PhoenixPE\Core\211-Registry.script
[  6/ 21] Core Config v1.2.1.0            |   2.2s | PhoenixPE\Core\212-ShellConfig.script
[  7/ 21] Core WoW64 v1.0.3.0             |  61.0s | PhoenixPE\Core\251-WoW64.script
[  8/ 21] PreShell v1.2.1.0               |   2.2s | PhoenixPE\Shell\000-PreShell.script
[  9/ 21] Explorer Shell v1.7.3.0         |  60.7s | PhoenixPE\Shell\001-Explorer.script
[ 10/ 21] StartAllBack v1.2.1.0           |   3.5s | PhoenixPE\Shell\051-StartAllBack.script
[ 11/ 21] Networking v1.8.0.0             |  46.8s | PhoenixPE\Components\310-Networking.script
[ 12/ 21] PENetwork Manager v1.7.2.0      |   2.8s | PhoenixPE\Components\310-PENetwork.script
[ 13/ 21] Audio v1.3.0.0                  |  14.4s | PhoenixPE\Components\320-Audio.script
[ 14/ 21] Arsenal Image Mounter v1.1.4.0  |   7.0s | PhoenixPE\Components\330-AimRamdisk.script
[ 15/ 21] MMC Snap-Ins v1.4.1.0           |  13.7s | PhoenixPE\Components\MMC.script
[ 16/ 21] Task Manager v1.0.0.0           |   0.8s | PhoenixPE\Components\TaskMgr.script
[ 17/ 21] Windows PowerShell v1.1.1.0     |   3.1s | PhoenixPE\Components\WindowsPowerShell.script
[ 18/ 21] .NET Framework v1.3.1.0         |  17.6s | PhoenixPE\Components\.NET Runtime\DotNETFx.script
[ 19/ 21] Visual C++ 14 Runtime v1.6.0.0  |   0.6s | PhoenixPE\Components\Visual C++ Runtime\350-VCRedist-14.script
[ 20/ 21] Visual C++ 8-9 Runtime v1.0.2.0 |  11.0s | PhoenixPE\Components\Visual C++ Runtime\350-VCRedist-Embedded.script
[ 21/ 21] Localization v1.4.0.0           |   2.9s | PhoenixPE\Tweaks\410-Localization.script


<Referenced Scripts>
[ Macro ] PhoenixPE API v1.13.0.0                  | PhoenixPE\PhoenixAPI.script


<Variables>
- Fixed Variables
%BaseDir% = D:\PhoenixPE
%EngineVersion% = 100
%PEBakery% = True
%PEBakeryVersion% = 1.2.0
%ProjectTitle% = PhoenixPE
%Version% = 082

- Global Variables
%API% = D:\PhoenixPE\Projects\PhoenixPE\PhoenixAPI.script
%APIVAR% = Macros
%ISODir% = 
%ISOFile% = 
%OutputDir% = 
%PEPrograms% = 
%ProgramsCache% = %Workbench%\%ProjectTitle%\Programs
%ProjectCache% = %Workbench%\%ProjectTitle%\Cache
%ProjectDir% = %BaseDir%\Projects\PhoenixPE
%ProjectTemp% = %Workbench%\%ProjectTitle%\Temp
%RegComponents% = %TargetDir%\Windows\System32\config\Components
%RegDefault% = %TargetDir%\Windows\System32\config\Default
%RegDrivers% = %TargetDir%\Windows\System32\config\Drivers
%RegInstallComponents% = %RegistryCache%\Install\Components
%RegInstallDefault% = %RegistryCache%\Install\Default
%RegInstallDrivers% = %RegistryCache%\Install\Drivers
%RegInstallSoftware% = %RegistryCache%\Install\Software
%RegInstallSystem% = %RegistryCache%\Install\System
%RegSoftware% = %TargetDir%\Windows\System32\config\Software
%RegSystem% = %TargetDir%\Windows\System32\config\System
%RegistryCache% = %ProjectCache%\Hives
%RegistryDriversSource% = Boot.wim
%RegistrySoftwareSource% = Install.wim
%Shell% = 
%SourceArch% = x64
%SourceBaseWim% = D:\PhoenixPE\source\Sources\Boot.wim
%SourceBaseWimImage% = 2
%SourceBaseWimName% = Boot.wim
%SourceDir% = D:\PhoenixPE\source
%SourceFallbackLang% = fr-FR|en-US
%SourceInstallWim% = D:\PhoenixPE\source\Sources\Install.wim
%SourceInstallWimImage% = 6
%SourceLang% = fr-FR
%SourceVer% = 10.0.22621.2428
%TargetAppData% = %TargetDir%\Users\Default\AppData\Roaming
%TargetBootWim% = %OutputDir%\Sources\Boot.wim
%TargetDir% = %Workbench%\%ProjectTitle%\Target
%TargetLocalAppData% = %TargetDir%\Users\Default\AppData\Local
%TargetPrograms% = 
%TargetSystem32% = %TargetDir%\WINDOWS\System32
%TargetWindows% = %TargetDir%\WINDOWS
%Tools% = %BaseDir%\Projects\%ProjectTitle%\Tools
%Workbench% = %BaseDir%\Workbench
</code></pre>
</details>
