### ISSUE TITLE
VSS "restore defaults" does not restore defaults.

### ISSUE THREAD

**Issue by ElektroStudios** [PhoenixPE/PhoenixPE#43]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
Issue urgency: lowest

Very simple issue this time:

In the VSS script, the "Auto start Volume Shadow Copy service" checkbox is checked by default, however, the "Restore defaults" button will uncheck this checkbox.

Maybe this thing alone has not enough relevancy for making a issue report, and it's not my intention to report every little flaw that I find, but things like this make me wonder if I now press "Restore defaults" on every script of the project, all scripts will remain configured as designed by default and everything will work as expected during the build procedure?.

Note: _please take into account that at the moment of writing this I'm not really aware whether the VSS script belongs to your own, or maybe to PEBakery predefined scripts (if any) or something else. I don't use PEBakery outside PhoenixPE project files._

**Comment by homes32** [comment]
> Maybe this thing alone has not enough relevancy for making a issue report, and it's not my intention to report every little flaw that I find, but things like this make me wonder if I now press "Restore defaults" on every script of the project, all scripts will remain configured as designed by default and everything will work as expected during the build procedure?.

Since this script hasn't been modified in over 3 years and has it's original version number, its likely I simply forgot to reset the defaults after testing the auto-start feature. I do make a habit of using the "Restore Defaults" button myself before I commit and push any changes to a script, so the "feature" is reliable, but if you do find any other instances where something does not appear to be working as it should please feel free to continue to post them.
