### ISSUE TITLE
Various issues with Simplewall script.

### ISSUE THREAD

**Issue by ElektroStudios** [PhoenixPE/PhoenixPE#44]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
Issue urgency: medium

1. Simplewall will always run on shell startup regardless of the script settings, if I for example uncheck all these three checkboxes:

![](https://i.imgur.com/M7dpM5O.png)

2. The "Download the latest rules and translations" setting seems not working as expected, because Simplewall always finds and warns to download a new rule set at shell startup.

_At the time of writing this, I have not yet tried to get rid of issues 1 and 2 by providing a custom simplewall config file._

**Expected Behavior**
Allow the user to create the simplewall shortcuts while preventing simplewall from running at startup if not configured to do it by the user.

**Comment by homes32** [comment]
I've identified the issues with the rules and translations url's but I cannot reproduce issue 1, where simplewall run's with the check boxes disabled. 

Did you run the script once with checkboxes enabled, then disable them and run the script again (without rebuilding the project) and just rebuild .wim + iso? If so that's the cause of the issue. The way the autorun works with PECMD, PhoenixPE simply appends the autorun entry to the end of the appropriate PECMD section. It cannot remove entries that already exist from a previous run, as it can't possibly know which entries are safe to remove and which a user or other script might have added either manually or during another script execution.

**Comment by ElektroStudios** [comment]
> Did you run the script once with checkboxes enabled, then disable them and run the script again  (without rebuilding the project) and just rebuild .wim + iso?

Hi. I always do a full build procedure for all of these tests by pressing the build button in the UI.

I'm not sure how to reproduce again the behavior I described, I spent quite some time trying to get "simplewall" to work as expected.

Now I have unchecked all three boxes again to generate the support log, but to my surprise when I loaded the OS this time simplewall does not ran at startup. 

So I suppose that this will have been a very rare isolated case, and the issue can be considered closed.

Thanks for your support!
