### ISSUE TITLE
Multiboot ISO

### ISSUE THREAD

**Issue by lodarmayarder** [PhoenixPE/PhoenixPE#55]
﻿

Checklist
---------
- [ x] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

**Describe the solution you'd like**
Thank you for the work done. 👍 
Will it be possible to make a multiboot iso with x86 and x64 as well as grub?
This will make it possible to include additional tools.
This feature was already finding its audience on older constructions :
http://w7pese.cwcodes.net/Projects/Win7PESE/OtherOS/zMultiWim.script
https://reboot.pro/index.php?showtopic=13780&page=2

**Describe why you believe your suggestion would benefit the project and members of the community at large**
 
**Describe alternatives you've considered**
Ventoy but its not an iso

**Additional context**
This bootable iso is may be  solution 
https://usbtor.ru/viewtopic.php?t=470

**Comment by homes32** [comment]
To be honest, I really don't see this happening in the near future. At one time years ago I wanted to include some sort of multi-boot functionality like the earlier projects such as LiveXP, VistaPE, even Win7PE, however a lot has changed since those days and the cost (time)/benefit doesn't align with the alternatives available.

Most recovery is now done through PXE boot (corp. networks, labs, repair shops, etc.) or USB drives, which are now relatively inexpensive and come in large sizes. Most modern computers don't even come with CD/DVD drives anymore, though external USB drives are inexpensive.

Everyone (including myself) seems to want something different in a multiboot environment. some like dead simple loaders like plop. some like syslinux, some like grub and it's variants, some want nested password protected menus, floppy images, UEFI images (memtest), etc. There is no foolproof way to cobble together something most would be happy with, would be easy to use, and wouldn't require alot of maint. overhead.

Tools like Ventoy, YUMI, SARDU, etc. make it stupid easy to create multiboot USB drives out of whatever you can throw at them, or for those like me who want to be anal, we hand customize our bootloaders and just update .wim images, etc as needed (see Media Creation > Copy Files script).

**Comment by lodarmayarder** [comment]
Thank you for the quick reply.
Do you think it is possible that I modify "700-BCD.script" script in order to configure the bootloader to luanch a second "boot.wim" file located in "Sources" folder ?

**Comment by homes32** [comment]
> Thank you for the quick reply. Do you think it is possible that I modify "700-BCD.script" script in order to configure the bootloader to luanch a second "boot.wim" file located in "Sources" folder ?

That's where I would probably start experimenting.
You will also want to make use of the Source Config > Advanced Options > Ext. Programs Folder option to set a different name for the Programs folder (ex. Programs-x64, Programs-x86) when you build the project for your x86 and x64 ISO files
