### ISSUE TITLE
boot loader PECMD.exe vs PhoenixPE.au3 - i like to have pecmd back/too in the release

### ISSUE THREAD

**Issue by Whatslp** [PhoenixPE/PhoenixPE#76]
Checklist
---------
- [x] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

I would like to have pecmd back, at least the possibility to choose between the new and the old boot loader.
In the previous version there was a switch (%_PhoenixAPI_ConfigMode%=PECMD).
The new au3 script reminds me of all the problems that come with au3 like the previous versions (vpleldr.au3/w7ldr.au3).
Au3 is not very good at error handling. In the past i had to use an older au3 version to force an script to ignore errors and continue, which in the case of a boot loader is the most important thing.
The boot process crashes with the new version (auto reboot after pressing okay), at the moment there is a syntax that au3 does not like. I had to make several changes to my scripts to get it to work (double quotas instead of single quotas).
As far as I know, pecmd is also open source, and has worked very well over the last few years.
I know you introduced new commands for the support of your new version.

Every thing else in the new release is the most stable und best version i ever had since the beginning (bartpe and co.). Thank you for that.

**Comment by VanFlusen** [comment]
You can find some answers in the last post:

https://theoven.org/viewtopic.php?t=169&start=120

**Comment by homes32** [comment]
Post https://theoven.org/viewtopic.php?p=1594#p1594 to be specific, but I'll summarize here as well for other's that may run across this ticket.

> I would like to have pecmd back, at least the possibility to choose between the new and the old boot loader. In the previous version there was a switch (%_PhoenixAPI_ConfigMode%=PECMD). 

Not going to happen. I have neither the time or desire to support 2 completely different loaders. Lots of time an effort goes into development of PhoenixPE. For prospective, each feature that's developed if it takes for an hour to map out and code, takes an additional 2+ hours to fully test and debug all scenarios before I'll release it. We are already supporting 2 different Windows versions (10/11), and roughly 150 app scripts, not counting component/features/tweaks or all the backend core scripts and API's. And before each release, every single script is tested with multiple sources/builds. I develop PhoenixPE for fun in my limited free time so double the current development workload to split the user base and creating double opportunity for problems resulting in double the support load on top of that is not my definition of fun :) and will lead to QA and instability issues across the project like it has in past projects that offer too many conflicting/incompatible options. It may not seem like a big deal for app scripts who just need AddAutoRun or AddShortcut, but it's a big deal when your talking about what goes on under the hood for the Core project.

In order to keep innovating and improving, I need a stable, unified base to work on.

In regards to the `%_PhoenixAPI_ConfigMode%=PECMD` variable present in earlier versions of the PhoenixAPI, when I first created the API I was hesitant to use PECMD to begin with. This variable was created as a way for me to test different methods in the development process and it became clear very quickly that a split loader was not maintainable to my standards.

Now for the good news. For backwards compatibility the PECMD interpreter is still included in PhoenixPE and will be for the foreseeable future as an alternate means of customization. It is also possible to run PECMD scripts automatically during the Pre-Config stage by including a PhoenixPE-UserConfig.ini/wcz/wcz file in System32 or running them directly with AddAutoRun. In addition you can also run un-compiled Autoit .au3 and binary .a3x scripts during boot as well with the included AutoIt3 interpreter.

>The new au3 script reminds me of all the problems that come with au3 like the previous versions (vpleldr.au3/w7ldr.au3). Au3 is not very good at error handling. In the past i had to use an older au3 version to force an script to ignore errors and continue, which in the case of a boot loader is the most important thing. 
>
>The boot process crashes with the new version (auto reboot after pressing okay), at the moment there is a syntax that au3 does not like. I had to make several changes to my scripts to get it to work (double quotas instead of single quotas). 

This is a legitimate concern. There are some things I have been working on, such as syntax checking during the finalize build process that will hopefully minimize some of these instances. and as always, in the case where you are developing your own customization, you also take on the responsibility of proper testing and debugging. I am open to suggestions on what you think would be helpful to have happen in these types of situations. There is always room for improvement.

>As far as I know, pecmd is also open source, 

PECMD hasn't been open source for **well** over a decade. The latest available source is from 2007, suffice to say, it is missing alot of functionality.

> Every thing else in the new release is the most stable und best version i ever had since the beginning (bartpe and co.). Thank you for that.

That's great to hear! I spend a lot of time and effort on quality and stability. It sometimes takes longer but the end result is something I hope people can enjoy using.

Thanks for the feedback.
