### ISSUE TITLE
use PhoenixPE as bootable WinPE environment for subsequent builds

### ISSUE THREAD

**Issue by rezad1393** [PhoenixPE/PhoenixPE#90]
Checklist
---------
- [x] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

**Describe the solution you'd like**
A clear and concise description of what you would like to see implemented.
support for running this app via wine (bottles) on linux

**Describe why you believe your suggestion would benefit the project and members of the community at large**
helps those that dont have windows create winpe
 
**Describe alternatives you've considered**
running this app in a VM. and windows 11 cant be emulated with qemu right now easily as it says HW not supported

running the app in winpe via VM. doesnt run.

**Additional context**

**Comment by rezad1393** [comment]
maybe trying to make this app run in winpe be better.

**Comment by homes32** [comment]
This is unlikely to happen with Wine due to dependencies like DISM and powershell.

It is possible to run in WinPE/PhoenixPE, but you need the .Net6 runtime and powershell installed. for all the effort/resources it takes your probably better off with vmware player or VirtualBox and a full install though.

**Comment by rezad1393** [comment]
> This is unlikely to happen with Wine due to dependencies like DISM and powershell.
> 
> It is possible to run in WinPE/PhoenixPE, but you need the .Net6 runtime and powershell installed. for all the effort/resources it takes your probably better off with vmware player or VirtualBox and a full install though.

I can understand the wine part but not the .net part.

when I select .net6 and powershell in option to build the image and then use that image too boot and then try the app on that winepe it didnt work.

I will try again and post the errors here.

**Comment by homes32** [comment]
you need the v1 powershell included with windows, not the powershell core script included with PhoenixPE.

There is currently not a script for v1 but you can run the following in codebox or tweakbox
```
RegLoadHives
RegWrite,HKLM,REG_EXPAND_SZ,"Tmp_Software\Microsoft\Windows\CurrentVersion\App Paths\PowerShell.exe","","%SystemRoot%\system32\WindowsPowerShell\v1.0\PowerShell.exe"

// Add to system PATH
RegRead,HKLM,"Tmp_System\ControlSet001\Control\Session Manager\Environment","Path",%SysPath%
StrFormat,CTrim,%SysPath%,";",%SysPath%
RegWrite,HKLM,0x2,"Tmp_System\ControlSet001\Control\Session Manager\Environment","Path","%SysPath%;%SystemRoot%\system32\WindowsPowerShell\v1.0\;"

RegUnloadHives

RequireFile,\Windows\System32\WindowsPowerShell

```

**Comment by rezad1393** [comment]
> you need the v1 powershell included with windows, not the powershell core script included with PhoenixPE.
> 
> There is currently not a script for v1 but you can run the following in codebox or tweakbox
> 
> ```
> RegLoadHives
> RegWrite,HKLM,REG_EXPAND_SZ,"Tmp_Software\Microsoft\Windows\CurrentVersion\App Paths\PowerShell.exe","","%SystemRoot%\system32\WindowsPowerShell\v1.0\PowerShell.exe"
> 
> // Add to system PATH
> RegRead,HKLM,"Tmp_System\ControlSet001\Control\Session Manager\Environment","Path",%SysPath%
> StrFormat,CTrim,%SysPath%,";",%SysPath%
> RegWrite,HKLM,0x2,"Tmp_System\ControlSet001\Control\Session Manager\Environment","Path","%SysPath%;%SystemRoot%\system32\WindowsPowerShell\v1.0\;"
> 
> RegUnloadHives
> 
> RequireFile,\Windows\System32\WindowsPowerShell
> ```
> 
> also note that you will need to have the pebakery/phoenixpe target on a removable media. It won't work with ramdrive or FBWF/UWF

I have set the app on removable drive (another hard drive).

can the first part be done internally so that I can run this app on the image build by app  so that at most I need windows once.?

**Comment by homes32** [comment]
> can the first part be done internally so that I can run this app on the image build by app so that at most I need windows once.?

I've added the WindowsPowershell component as a script. It will be included in the next release.

**Comment by rezad1393** [comment]
> > can the first part be done internally so that I can run this app on the image build by app so that at most I need windows once.?
> 
> I've added the WindowsPowershell component as a script. It will be included in the next release.

can you maybe test the image created and boot it to see if it can create another image from the app running in that boot?

**Comment by homes32** [comment]
I was able to successfully build the base project using the new Windows Powershell script (grab it from the master branch or wait for the upcoming release).

A couple things of note:
1. make sure to include the .net 6 script unless you are using the phoenixPE package with the included runtime. 
2. include the WIndows Powershell script
3. International options (Tweaks > Localization) must be configured manually instead of using the HostOS or Default options. Online DISM servicing options are restricted in WinPE.
4. the output directory must be on an external drive. Wim & DISM will not apply to a virtual filesystem like a ramdrive or FBWF/UWF.

**Comment by rezad1393** [comment]
when I started this issue, I asked about wine support. Now I think it may not be possible on wine but...
if that is not possible and you are talking about running this app on an image build by this app, please specify it so that I know.

1- I understand the first part but not the second part. If you mean am I using the standalone app the answer is yes. so I dont need to include .net6 or do the winpe created may still need .net6 included? should be prudent and just include it to be sure?

2- I have done that.
3- I will try.
4- do you mean that I need to for example add a usb drive to my laptop and then run the qemu app (virtualizer for linux) or do you mean I need to add a virtual drive (which is an hdd in the VM) to be writable?

**Comment by homes32** [comment]
I am referring to the ability to build PhoenixPE once on a windows computer or VM and use it as bootable WinPE environment for subsequent builds. THis allows you to bypass the emulator and make full use of the available CPU and RAM.

1. There are 2 download options for the packaged release of PhoenixPE. the `PhoenixPE-x.x.x-rt` and `PhoenixPE-x.x.x-x64`. the `-rt` release does not include the .net 6 runtime needed by PEBakery to function; it is assumed you have this installed in your OS. If you are using this release you must select the .Net 6 runtime when you build PhoenixPE on a windows computer for the first time. If you are using the `-x64` release, then the .net 6 runtime is included in the package and you don't need to include it in your build unless other applications require it.

4. I mean that if you are running inside PhoenixPE after building it and trying to build more builds then you must not run PhoenixPE from a ramdisk or from the `X:\` drive or the build will fail. Place the PhoenixPE folder on a USB hard-drive or an NTFS partition.


running on wine I don't believe is possible due to the dependence on WindowsPowershell (not the core version) and DISM.

hope that helps.

**Comment by rezad1393** [comment]
> I am referring to the ability to build PhoenixPE once on a windows computer or VM and use it as bootable WinPE environment for subsequent builds. THis allows you to bypass the emulator and make full use of the available CPU and RAM.
> 
>     1. There are 2 download options for the packaged release of PhoenixPE. the `PhoenixPE-x.x.x-rt` and `PhoenixPE-x.x.x-x64`. the `-rt` release does not include the .net 6 runtime needed by PEBakery to function; it is assumed you have this installed in your OS. If you are using this release you must select the .Net 6 runtime when you build PhoenixPE on a windows computer for the first time. If you are using the `-x64` release, then the .net 6 runtime is included in the package and you don't need to include it in your build unless other applications require it.
> 
>     2. I mean that if you are running inside PhoenixPE after building it and trying to build more builds then you must not run PhoenixPE from a ramdisk or from the `X:\` drive or the build will fail. Place the PhoenixPE folder on a USB hard-drive or an NTFS partition.
> 
> 
> running on wine I don't believe is possible due to the dependence on WindowsPowershell (not the core version) and DISM.
> 
> hope that helps.

1- I use the standalone version.
2-I am doing that but via VM. I dont understand the issue with "x:\" drive. (not really using windows daily) is that the CD drive issue?
when I run a VM via qemu I attack a writable virtual drive as file to it which shows up as hdd (if I remember correctly) which in a running normal windows (in VM) is writable. I store the app folder there.


btw I still cant run this produced image on an my actual laptop. It just runs on VM.
maybe it needs secure boot which I disabled. if so why that russian winpe works?
